from pathlib import Path
from pulumi.dynamic import Resource
from pulumi.dynamic.dynamic import CreateResult, DiffResult, ResourceProvider
from typing import Any, Optional, Dict
from pulumi import Input, ResourceOptions

src_dir = "src"
exports_file_path = Path(src_dir).joinpath("aws-exports.js")


class AmplifyExportsFile(Resource):
    def __init__(self,
            name: str,
            props: Dict[str,str],
            opts: Optional[ResourceOptions] = None):
        super().__init__(AmplifyExportsFileProvider(), name, props, opts)


class AmplifyExportsFileProvider(ResourceProvider):
    def create(self, inputs: Dict[str,Any]) -> CreateResult:
        file_inputs = inputs.copy()
        file_inputs.pop("__provider")

        file_content = [
            "/* eslint-disable */",
            "// WARNING: DO NOT EDIT. This file is automatically generated by Pulumi Amplify. It will be overwritten.",
            "",
            "const awsmobile = {",
            *[ f'    "{key}": "{file_inputs[key]}",' for key in file_inputs.keys() ],
            "};",
            "",
            "",
            "export default awsmobile;",
        ]
        exports_file_path.write_text("\n".join(file_content))
        print(exports_file_path.name)

        return CreateResult(exports_file_path.name, {})

    def diff(self, id, olds, news):
        return DiffResult(
            changes=True,
            replaces=olds.keys(),
            delete_before_replace=True
        )
    
    def delete(self, id, props):
        exports_file_path.unlink()
        pass
